# Tells the embedded web server to open and listen for networking traffic on port 8080
server.port=8080

# In-memory connection string mapping out a virtual temporary schema named 'mediadb'
spring.datasource.url=jdbc:h2:mem:mediadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Exposes a browser-ready user interface to look at your database rows visually at http://localhost:8080/h2-console
spring.h2.console.enabled=true

# Debugging Feature: Instructs Hibernate to print out the raw SQL statements directly in your
# IntelliJ console window whenever you make an API call from Postman
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto=update: Tells Hibernate to look at your Java code files and automatically create or
# modify the SQL tables to match your properties every single time the application boots up
spring.jpa.hibernate.ddl-auto=update

# Tells Spring Boot NEVER to look for or execute manual sql scripts (like schema.sql or data.sql).
# This completely prevents the empty script crash and forces the system to rely purely on your Java entities.
spring.sql.init.mode=never